Seed 3 failed: (sqlite3.OperationalError) table study_user_attributes already exists
[SQL: 
CREATE TABLE study_user_attributes (
	study_user_attribute_id INTEGER NOT NULL, 
	study_id INTEGER, 
	"key" VARCHAR(512), 
	value_json TEXT, 
	PRIMARY KEY (study_user_attribute_id), 
	UNIQUE (study_id, "key"), 
	FOREIGN KEY(study_id) REFERENCES studies (study_id)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
