Found local copy...
Loading...
Done!
[I 2025-09-06 02:37:32,797] A new study created in RDB with name: __init__
[I 2025-09-06 02:37:33,106] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_0
[I 2025-09-06 02:37:33,129] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_1
[I 2025-09-06 02:37:33,148] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_2
[I 2025-09-06 02:37:33,196] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_3
[I 2025-09-06 02:37:47,805] Trial 0 finished with value: 0.5541089773178101 and parameters: {'n_estimators': 50, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5541089773178101.
[I 2025-09-06 02:37:56,801] Trial 0 finished with value: 0.5598791241645813 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5598791241645813.
[I 2025-09-06 02:38:03,883] Trial 0 finished with value: 0.5549521446228027 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5549521446228027.
[I 2025-09-06 02:38:20,687] Trial 1 finished with value: 0.5550955533981323 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5549521446228027.
[I 2025-09-06 02:38:23,468] Trial 0 finished with value: 0.5460618734359741 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:38:23,712] Trial 1 finished with value: 0.561255693435669 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5541089773178101.
[I 2025-09-06 02:38:32,018] Trial 1 finished with value: 0.5552790760993958 and parameters: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.5552790760993958.
[I 2025-09-06 02:38:33,931] Trial 1 finished with value: 0.5486485958099365 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:38:46,007] Trial 2 finished with value: 0.5492852330207825 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:38:51,789] Trial 2 finished with value: 0.5571890473365784 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.5552790760993958.
[I 2025-09-06 02:39:31,287] Trial 2 finished with value: 0.5550955533981323 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5549521446228027.
[I 2025-09-06 02:39:31,325] Trial 2 finished with value: 0.556265652179718 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5541089773178101.
[I 2025-09-06 02:39:31,357] Trial 3 finished with value: 0.5533519387245178 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:40:09,952] Trial 3 finished with value: 0.5549521446228027 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5541089773178101.
[I 2025-09-06 02:40:09,989] Trial 4 finished with value: 0.5477251410484314 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:40:10,006] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_4
[I 2025-09-06 02:40:10,031] Trial 3 finished with value: 0.5550324320793152 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:40:32,013] Trial 0 finished with value: 0.5508854985237122 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5508854985237122.
[I 2025-09-06 02:41:29,956] Trial 4 finished with value: 0.5558124780654907 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:41:29,964] Trial 1 finished with value: 0.552548885345459 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5508854985237122.
[I 2025-09-06 02:41:29,979] Trial 4 finished with value: 0.5547456741333008 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5541089773178101.
[I 2025-09-06 02:41:30,096] Trial 5 finished with value: 0.5465551018714905 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:42:24,206] Trial 2 finished with value: 0.5526922941207886 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5508854985237122.
[I 2025-09-06 02:42:24,238] Trial 5 finished with value: 0.5570055246353149 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5541089773178101.
[I 2025-09-06 02:42:24,254] Trial 5 finished with value: 0.5531224012374878 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 5 with value: 0.5531224012374878.
[I 2025-09-06 02:42:57,550] Trial 6 finished with value: 0.5476219058036804 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:42:57,577] Trial 6 finished with value: 0.5526291131973267 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.5526291131973267.
[I 2025-09-06 02:42:57,600] Trial 6 finished with value: 0.5615023970603943 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5541089773178101.
[I 2025-09-06 02:42:57,707] Trial 3 finished with value: 0.5510289072990417 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5508854985237122.
[I 2025-09-06 02:43:08,978] Trial 7 finished with value: 0.5468418598175049 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:43:09,039] Trial 7 finished with value: 0.5620357990264893 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.5526291131973267.
[I 2025-09-06 02:43:28,388] Trial 7 finished with value: 0.5571891069412231 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5541089773178101.
[I 2025-09-06 02:43:28,407] Trial 4 finished with value: 0.5506388545036316 and parameters: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 4 with value: 0.5506388545036316.
[W 2025-09-06 02:43:28,414] Trial 8 failed with parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (35,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 274, in get_hyperparameter_space
    'min_samples_leaf': trial.suggest_categorical('min_samples_leaf', [1, 2, 4]),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-06 02:43:28,420] Trial 8 failed with value None.
[I 2025-09-06 02:43:34,431] Trial 8 finished with value: 0.5468418598175049 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:43:40,855] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_5
[I 2025-09-06 02:44:04,939] Trial 5 finished with value: 0.5488321185112 and parameters: {'n_estimators': 50, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 5 with value: 0.5488321185112.
[I 2025-09-06 02:44:04,963] Trial 9 finished with value: 0.5468418598175049 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5460618734359741.
[I 2025-09-06 02:44:05,003] Trial 8 finished with value: 0.5561222434043884 and parameters: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5541089773178101.
[I 2025-09-06 02:45:14,596] Trial 10 finished with value: 0.5456717610359192 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 10 with value: 0.5456717610359192.
[I 2025-09-06 02:45:14,607] Trial 6 finished with value: 0.5519121289253235 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 5 with value: 0.5488321185112.
[I 2025-09-06 02:45:14,613] Trial 0 finished with value: 0.5600454807281494 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5600454807281494.
[I 2025-09-06 02:45:14,634] Trial 9 finished with value: 0.5526922941207886 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 9 with value: 0.5526922941207886.
[W 2025-09-06 02:45:36,478] Trial 10 failed with parameters: {'n_estimators': 100} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (45,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 272, in get_hyperparameter_space
    'max_depth': trial.suggest_categorical('max_depth', [None, 5, 10, 15, 20]),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-06 02:45:36,482] Trial 10 failed with value None.
[W 2025-09-06 02:45:36,517] Trial 11 failed with parameters: {'n_estimators': 100, 'max_depth': 15} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (44,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 273, in get_hyperparameter_space
    'min_samples_split': trial.suggest_categorical('min_samples_split', [2, 5, 10]),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-06 02:45:36,521] Trial 11 failed with value None.
[I 2025-09-06 02:45:50,913] Trial 7 finished with value: 0.5486887693405151 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5486887693405151.
[I 2025-09-06 02:45:50,933] Trial 1 finished with value: 0.5532887578010559 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.5532887578010559.
[I 2025-09-06 02:45:50,934] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_7
[I 2025-09-06 02:45:50,958] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_6
[I 2025-09-06 02:46:29,476] Trial 8 finished with value: 0.5514189004898071 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5486887693405151.
[I 2025-09-06 02:46:29,496] Trial 0 finished with value: 0.5518319606781006 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5518319606781006.
[I 2025-09-06 02:46:29,596] Trial 2 finished with value: 0.5512354373931885 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.5512354373931885.
[I 2025-09-06 02:46:29,718] Trial 0 finished with value: 0.5525087118148804 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5525087118148804.
[I 2025-09-06 02:46:55,057] Trial 9 finished with value: 0.5534723401069641 and parameters: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5486887693405151.
[W 2025-09-06 02:46:55,071] Trial 1 failed with parameters: {'n_estimators': 100} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (53,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 272, in get_hyperparameter_space
    'max_depth': trial.suggest_categorical('max_depth', [None, 5, 10, 15, 20]),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-06 02:46:55,072] Trial 1 failed with value None.
[I 2025-09-06 02:46:55,124] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_8
[I 2025-09-06 02:46:55,831] Trial 1 finished with value: 0.5488952398300171 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.5488952398300171.
[I 2025-09-06 02:47:02,174] Trial 0 finished with value: 0.5584222078323364 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5584222078323364.
[I 2025-09-06 02:47:13,648] Trial 1 finished with value: 0.558462381362915 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5584222078323364.
[I 2025-09-06 02:47:18,906] Trial 3 finished with value: 0.5589156150817871 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.5512354373931885.
[I 2025-09-06 02:47:29,950] Trial 10 finished with value: 0.5539254546165466 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5486887693405151.
[I 2025-09-06 02:47:46,223] Trial 2 finished with value: 0.5517286658287048 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.5488952398300171.
[I 2025-09-06 02:48:10,610] Trial 2 finished with value: 0.5559157133102417 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.5559157133102417.
[I 2025-09-06 02:48:13,103] Trial 4 finished with value: 0.55265212059021 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.5512354373931885.
[I 2025-09-06 02:48:18,566] Trial 11 finished with value: 0.5511321425437927 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 7 with value: 0.5486887693405151.
[I 2025-09-06 02:48:20,708] Trial 3 finished with value: 0.5505586266517639 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.5488952398300171.
[I 2025-09-06 02:48:27,114] Trial 3 finished with value: 0.5550324320793152 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:48:34,835] Trial 4 finished with value: 0.5514419078826904 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.5488952398300171.
[I 2025-09-06 02:48:34,920] Trial 12 finished with value: 0.5515221953392029 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 7 with value: 0.5486887693405151.
[I 2025-09-06 02:48:43,943] Trial 5 finished with value: 0.5545219779014587 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.5488952398300171.
[I 2025-09-06 02:48:48,049] Trial 5 finished with value: 0.5494688153266907 and parameters: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 5 with value: 0.5494688153266907.
[I 2025-09-06 02:48:53,324] Trial 6 finished with value: 0.547868549823761 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.547868549823761.
[I 2025-09-06 02:48:56,053] Trial 4 finished with value: 0.5552790760993958 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:49:04,490] Trial 7 finished with value: 0.5439453125 and parameters: {'n_estimators': 50, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5439453125.
[I 2025-09-06 02:49:12,930] Trial 5 finished with value: 0.5582157373428345 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:49:15,023] Trial 8 finished with value: 0.5481553673744202 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.5439453125.
[I 2025-09-06 02:49:16,757] Trial 13 finished with value: 0.5515221953392029 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 7 with value: 0.5486887693405151.
[I 2025-09-06 02:49:18,906] Trial 6 finished with value: 0.5535755753517151 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 5 with value: 0.5494688153266907.
[I 2025-09-06 02:49:21,341] Trial 6 finished with value: 0.559099018573761 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:49:26,602] Trial 14 finished with value: 0.5521588921546936 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.5486887693405151.
[I 2025-09-06 02:49:27,740] Trial 7 finished with value: 0.5573955774307251 and parameters: {'n_estimators': 50, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 5 with value: 0.5494688153266907.
[I 2025-09-06 02:49:40,473] A new study created in RDB with name: MOL2VEC_RF_Pgp_Broccatelli_9
[I 2025-09-06 02:49:48,076] Trial 0 finished with value: 0.5539886951446533 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5539886951446533.
[I 2025-09-06 02:49:53,494] Trial 7 finished with value: 0.5556690692901611 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:49:58,324] Trial 1 finished with value: 0.5486486554145813 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:50:01,204] Trial 8 finished with value: 0.554172158241272 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 5 with value: 0.5494688153266907.
[I 2025-09-06 02:50:01,321] Trial 9 finished with value: 0.5517286658287048 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.5439453125.
[I 2025-09-06 02:50:08,924] Trial 9 finished with value: 0.5606821775436401 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 5 with value: 0.5494688153266907.
[I 2025-09-06 02:50:26,922] Trial 10 finished with value: 0.552015483379364 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 5 with value: 0.5494688153266907.
[I 2025-09-06 02:50:33,915] Trial 2 finished with value: 0.5501054525375366 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:50:37,516] Trial 10 finished with value: 0.5453219413757324 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5439453125.
[I 2025-09-06 02:50:44,621] Trial 8 finished with value: 0.5579289197921753 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:50:56,045] Trial 9 finished with value: 0.5610090494155884 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:50:58,204] Trial 3 finished with value: 0.5530421733856201 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:51:10,568] Trial 4 finished with value: 0.5512755513191223 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:51:11,577] Trial 10 finished with value: 0.5550324320793152 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:51:13,946] Trial 11 finished with value: 0.5453219413757324 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5439453125.
[I 2025-09-06 02:51:18,865] Trial 11 finished with value: 0.5488321185112 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.5488321185112.
[I 2025-09-06 02:51:28,340] Trial 5 finished with value: 0.5504553318023682 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:51:28,567] Trial 11 finished with value: 0.5550324320793152 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:51:38,699] Trial 6 finished with value: 0.5490385890007019 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:51:45,013] Trial 12 finished with value: 0.5550324320793152 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:51:51,426] Trial 12 finished with value: 0.5453219413757324 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5439453125.
[I 2025-09-06 02:52:02,093] Trial 13 finished with value: 0.5550324320793152 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:52:13,564] Trial 12 finished with value: 0.5488321185112 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.5488321185112.
[I 2025-09-06 02:52:13,814] Trial 7 finished with value: 0.5523654222488403 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:52:18,630] Trial 14 finished with value: 0.5550324320793152 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5550324320793152.
[I 2025-09-06 02:52:27,221] Trial 13 finished with value: 0.5453219413757324 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5439453125.
[I 2025-09-06 02:52:36,365] Trial 14 finished with value: 0.5476219654083252 and parameters: {'n_estimators': 50, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5439453125.
[I 2025-09-06 02:52:50,373] Trial 8 finished with value: 0.5494688153266907 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:52:50,400] Trial 13 finished with value: 0.5488321185112 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.5488321185112.
[I 2025-09-06 02:52:57,671] Trial 9 finished with value: 0.5490386486053467 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:53:04,959] Trial 10 finished with value: 0.5490385890007019 and parameters: {'n_estimators': 50, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:53:12,090] Trial 11 finished with value: 0.5486486554145813 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:53:13,325] Trial 14 finished with value: 0.5488321185112 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.5488321185112.
[I 2025-09-06 02:53:16,171] Trial 12 finished with value: 0.5486486554145813 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:53:20,164] Trial 13 finished with value: 0.5486486554145813 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.5486486554145813.
[I 2025-09-06 02:53:22,311] Trial 14 finished with value: 0.5486486554145813 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.5486486554145813.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 779, in get_trial
    trial_model = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (15,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    updated_state, values, warning_message = _tell_with_warning(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_tell.py", line 106, in _tell_with_warning
    frozen_trial = _get_frozen_trial(study, trial)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_tell.py", line 40, in _get_frozen_trial
    return study._storage.get_trial(trial_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 211, in get_trial
    return self._backend.get_trial(trial_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 780, in get_trial
    frozen_trial = self._build_frozen_trial_from_trial_model(trial_model)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 97, in run_single_experiment
    best_hyperparams = self.run_hyperparameter_optimization(
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 85, in run_hyperparameter_optimization
    study.optimize(objective, n_trials=env.N_TRIALS)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 490, in optimize
    _optimize(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial_id = _run_trial(study, func, catch)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    assert False, "Should not reach."
AssertionError: Should not reach.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/./code/main.py", line 18, in <module>
    manager.run_nested_cv(fingerprint, model_name, dataset_name)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 136, in run_nested_cv
    raise exc
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 131, in run_nested_cv
    seed_result, test_predictions, test_indices = future.result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
AssertionError: Should not reach.
